apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-service
  template:
    metadata:
      labels:
        app: quiz-service
    spec:
      containers:
        - name: quiz-service
          image: quiz-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: DB_HOST
              value: "mysql-service" #this should match
            - name: DB_PORT
              value: "3306" #default mysql port
            - name: DB_NAME
              value: "mydb"
            - name: DB_USER
              value: "user"
            - name: DB_PASSWORD
              value: "password"