apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-service
  template:
    metadata:
      labels:
        app: quiz-service
    spec:
      containers:
        - name: quiz-service
          image: quiz-service:new
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DB_DATA_SOURCE_URL
              value: jdbc:mysql://mysql-service:3306/mydb
            - name: DB_USER
              value: user
            - name: DB_PASSWORD
              value: password